apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Tham chiếu Base YAML
bases:
- ../../base

# 1. Thêm tiền tố vào tên tất cả tài nguyên
namePrefix: dev-

# 2. Thay đổi Image
images:
- name: nginx:1.23.0 # Tên image cũ trong base
  newTag: latest      # Tag mới cho Dev (nginx:latest)
