apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Tham chiếu Base YAML
bases:
- ../../base

# 1. Áp dụng Patch (vá)
patches:
- path: patch-replicas.yaml
  target:
    kind: Deployment
    name: nginx-deployment

# 2. Thêm một Annotation vào tất cả tài nguyên
commonAnnotations:
  sre/contact: production-team@example.com
